AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-env-vars

  Sample SAM Template for lambda-env-vars

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LambdaEnvVarsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: env_vars/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        LambdaEnvVars:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /env_vars
            Method: get
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: LambdaEnvVarsFunction
    Properties:
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref LambdaEnvVarsFunction]]
      RetentionInDays: 3

Outputs:
  # LambdaEnvVarsApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LambdaEnvVarsApi:
    Description: "API Gateway endpoint URL for Prod stage for Lambda Env Vars function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/env_vars/"
  LambdaEnvVarsFunction:
    Description: "Lambda Env Vars Function ARN"
    Value: !GetAtt LambdaEnvVarsFunction.Arn
  LambdaEnvVarsFunctionIamRole:
    Description: "Implicit IAM Role created for Lambda Env Vars function"
    Value: !GetAtt LambdaEnvVarsFunctionRole.Arn
  LambdaLogGroup:
    Description: "Cloudwatch Log Group ARN"
    Value: !Join ["", ["/aws/lambda/", !Ref LambdaEnvVarsFunction]]
